apiVersion: v1
kind: ReplicationController
metadata:
   name: elasticsearch-logging
   namespace: kube-system
   labels:
      k8s-app: elasticsearch-logging
      kubernetes.io/cluster-service: "true"
 
spec:
   replicas: 1
   selector:
      k8s-app: elasticsearch-logging
   template:
     metadata:
      labels:
         k8s-app: elasticsearch-logging
         version: v1
         kubernetes.io/cluster-service: "true"
     spec:
      containers:
      - image: elasticsearch:5.5
        name: elasticsearch-logging
        command: ["bin/elasticsearch"]
        args: ["-Ehttp.host=0.0.0.0", "-Etransport.host=127.0.0.1"] 
        ports:
         - containerPort: 9200
           name: es-port
           protocol: TCP
         - containerPort: 9300
           name: transport-port
           protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
      volumes:  
      - name: es-persistent-storage
        emptyDir: {}