apiVersion: v1
kind: ReplicationController
metadata:
   name: kibana-logging
   namespace: kube-system
   labels:
      k8s-app: kibana-logging
      kubernetes.io/cluster-service: "true"
spec:
   replicas: 1
   selector:
      k8s-app: kibana-logging
   template:
      metadata:
         labels:
            k8s-app: kibana-logging
            kubernetes.io/cluster-service: "true"
      spec:
         containers:
         - name: kibana
           image: docker.elastic.co/kibana/kibana:5.5.2
           ports:
           - name: kibana-port
             containerPort: 5601